// icons
const Icons = [
   { id: 1, label: '🙂' },
   { id: 2, label: '😀' },
   { id: 3, label: '😄' },
   { id: 4, label: '😆' },
   { id: 5, label: '😅' },
   { id: 6, label: '😂' },
   { id: 7, label: '🤣' },
   { id: 8, label: '😊' },
   { id: 9, label: '😉' },
   { id: 10, label: '😌' },
   { id: 11, label: '😏' },
   { id: 12, label: '😍' },
   { id: 13, label: '😘' },
   { id: 14, label: '😗' },
   { id: 15, label: '😙' },
   { id: 16, label: '😚' },
   { id: 17, label: '🤔' },
   { id: 18, label: '🙄' },
   { id: 19, label: '😠' },
   { id: 20, label: '😡' },
   { id: 21, label: '💩' },
   { id: 22, label: '😳' },
   { id: 23, label: '😝' },
   { id: 24, label: '😓' },
   { id: 25, label: '😢' },
   { id: 26, label: '😢' },
   { id: 27, label: '😭' },
   { id: 28, label: '😰' },
];
export { Icons };
